#Column specifications for the loan file
#After this initial setting, the data are saved to .rds. This will increase read in time later on.
#Lending Club Kaggle Data (2.2 mil Obs)
lc_data <- read_csv(file.path("C:","Users","henni","Documents","Data_Camp","Data","Lending_Club_Loan_Data","loan.csv"),
                    col_type= cols_only(loan_amnt = col_double(), funded_amnt = col_double(),funded_amnt_inv = col_double(),
                                        term=col_factor(), int_rate=col_double(), installment=col_double(), 
                                        grade=col_factor(levels=c( "A","B", "C", "D", "E", "F", "G"), ordered = T),
                                        sub_grade=col_factor(),emp_title=col_character(), emp_length=col_factor(),
                                        home_ownership=col_factor(),annual_inc=col_double(),verification_status=col_factor(),
                                        issue_d=col_date(format = "%b-%Y"), loan_status=col_factor(),pymnt_plan=col_factor(),
                                        purpose=col_character(),title=col_character(),zip_code=col_factor(),addr_state=col_factor(),
                                        dti = col_double(),delinq_2yrs = col_double(),earliest_cr_line = col_date(format = "%b-%Y"),
                                        inq_last_6mths=col_double(),mths_since_last_delinq=col_double(),
                                        mths_since_last_record=col_double(),open_acc=col_double(),pub_rec=col_double(),
                                        revol_bal=col_double(),revol_util=col_double(),total_acc=col_double(),
                                        initial_list_status=col_factor(),out_prncp=col_double(),out_prncp_inv=col_double(),
                                        total_pymnt=col_double(),total_pymnt_inv=col_double(),total_rec_prncp=col_double(),
                                        total_rec_int=col_double(),total_rec_late_fee=col_double(),recoveries=col_double(),
                                        collection_recovery_fee = col_double(),last_pymnt_d=col_date(format = "%b-%Y"),
                                        last_pymnt_amnt=col_double(),next_pymnt_d= col_date(format = "%b-%Y"),
                                        last_credit_pull_d = col_date(format = "%b-%Y"),collections_12_mths_ex_med = col_double(),
                                        mths_since_last_major_derog=col_double(),policy_code=col_double(),
                                        application_type=col_factor(),annual_inc_joint=col_double(),dti_joint = col_double(),
                                        verification_status_joint=col_factor(),acc_now_delinq = col_double(),tot_coll_amt=col_double(),
                                        tot_cur_bal=col_double(),open_acc_6m=col_double(),open_act_il=col_double(),
                                        open_il_12m=col_double(),open_il_24m=col_double(),mths_since_rcnt_il=col_double(),
                                        total_bal_il=col_double(),il_util = col_double(),open_rv_12m=col_double(),
                                        open_rv_24m=col_double(),max_bal_bc=col_double(),all_util=col_double(),
                                        total_rev_hi_lim=col_double(),inq_fi=col_double(),total_cu_tl=col_double(),
                                        inq_last_12m=col_double(),acc_open_past_24mths=col_double(),avg_cur_bal = col_double(),
                                        bc_open_to_buy = col_double(),bc_util = col_double(),chargeoff_within_12_mths = col_double(),
                                        delinq_amnt = col_double(),mo_sin_old_il_acct=col_double(),mo_sin_old_rev_tl_op=col_double(),
                                        mo_sin_rcnt_rev_tl_op=col_double(),mo_sin_rcnt_tl=col_double(),mort_acc=col_double(),
                                        mths_since_recent_bc=col_double(),mths_since_recent_bc_dlq=col_double(),
                                        mths_since_recent_inq=col_double(),mths_since_recent_revol_delinq=col_double(),
                                        num_accts_ever_120_pd=col_double(),num_actv_bc_tl=col_double(),
                                        num_actv_rev_tl=col_double(),num_bc_sats=col_double(),num_bc_tl=col_double(),
                                        num_il_tl=col_double(),num_op_rev_tl=col_double(),num_rev_accts=col_double(),
                                        num_rev_tl_bal_gt_0=col_double(),num_sats=col_double(),num_tl_120dpd_2m=col_double(),
                                        num_tl_30dpd=col_double(),num_tl_90g_dpd_24m=col_double(),num_tl_op_past_12m=col_double(),
                                        pct_tl_nvr_dlq=col_double(),percent_bc_gt_75=col_double(),pub_rec_bankruptcies=col_double(),
                                        tax_liens=col_double(),tot_hi_cred_lim=col_double(),total_bal_ex_mort=col_double(),
                                        total_bc_limit=col_double(),total_il_high_credit_limit=col_double(),
                                        revol_bal_joint=col_double(),sec_app_earliest_cr_line= col_date(format = "%b-%Y"),
                                        sec_app_inq_last_6mths=col_double(),sec_app_mort_acc=col_double(),
                                        sec_app_open_acc=col_double(), sec_app_revol_util=col_double(),
                                        sec_app_open_act_il=col_double(),sec_app_num_rev_accts=col_double(),
                                        sec_app_chargeoff_within_12_mths=col_double(),sec_app_collections_12_mths_ex_med=col_double(),
                                        sec_app_mths_since_last_major_derog=col_double(),hardship_flag=col_factor(),
                                        hardship_type=col_factor(),hardship_reason=col_character(),hardship_status=col_factor(),
                                        deferral_term=col_double(),hardship_amount=col_double(),
                                        hardship_start_date= col_date(format = "%b-%Y"),hardship_end_date= col_date(format = "%b-%Y"),
                                        payment_plan_start_date=col_date(format = "%b-%Y"),hardship_length=col_double(),
                                        hardship_dpd=col_double(),hardship_loan_status=col_factor(),
                                        orig_projected_additional_accrued_interest=col_double(),
                                        hardship_payoff_balance_amount=col_double(),hardship_last_payment_amount=col_double(),
                                        disbursement_method=col_factor(),debt_settlement_flag=col_factor(),
                                        debt_settlement_flag_date =col_date(format = "%b-%Y"),settlement_status=col_factor(),
                                        settlement_date=col_date(format = "%b-%Y"),settlement_amount=col_double(),
                                        settlement_percentage=col_double(),settlement_term=col_double())
)
write_rds(lc_data, file.path("C:","Users","henni","Documents","Data_Camp","Data","Lending_Club_Loan_Data","loan.rds"))
